public enum Brand {
	AUDI, BMW, CITROEN, MERCEDES, LADA, SUZUKI, TESLA, ISUZU, MITSUBISHI, TOYOTA, VELOREX, SUBARU, FORD, CHEVROLET, DACIA, ROLLS_ROYCE, OPEL, SKODA, RENAULT, NISSAN, SMART, KIA, MINI, OTHER;
}