
public enum City {
	ABA,ABÁDSZALÓK,ABAÚJSZÁNTÓ,ABONY,ÁCS,ADONY,AJAK,AJKA,ALBERTIRSA,ALSÓZSOLCA,ASZÓD,BÁBOLNA,BÁCSALMÁS,BADACSONYTOMAJ,BAJA,BAKTALÓRÁNTHÁZA,BALASSAGYARMAT,BALATONALMÁDI,BALATONBOGLÁR,
	BALATONFÖLDVÁR,BALATONFÜRED,BALATONFŰZFŐ,BALATONKENESE,BALATONLELLE,BALKÁNY,BALMAZÚJVÁROS,BARCS,BÁTASZÉK,BÁTONYTERENYE,BATTONYA,BÉKÉS,BÉKÉSCSABA,BÉLAPÁTFALVA,BELED,BERETTYÓÚJFALU,
	BERHIDA,BSENYSZÖG,BIATORBÁGY,BICSKE,BIHARKERESZTES,BODAJK,BÓLY,BONYHÁD,BORSODNÁDASD,BUDAKALÁSZ,BUDAKESZI,BUDAÖRS,BUDAPEST,BÜK,CEGLÉD,CELLDÖMÖLK,CIGÁND,CSÁKVÁR,CSANÁDPALOTA,CSENGER,
	CSEPREG,CSONRÁD,CSORNA,CSORVÁS,CSURGÓ,DABAS,DEBRECEN,DEMECSER,DERECSKE,DÉVAVÁNYA,DEVECSER,DIÓSD,DOMBÓVÁR,DOMBRÁD,DOROG,DUNAFÖLDVÁR,DUNAHARASZTI,DUNAKESZI,DUNAÚJVÁROS,DUNAVARSÁNY,
	DUNAVECSE,EDELÉNY,EGER,ELEK,EMŐD,ENCS,ENYING,ERCSI,ÉRD,ESZTERGOM,FEGYVERNEK,FEHÉRGYARMAT,FELSŐZSOLCA,FERTŐD,FERTŐSZENTMIKLÓS,FONYÓD,FÓT,FÜZESABONY,FÜZESGYARMAT,GÁRDONY,GÖD,GÖDÖLLŐ,
	GÖNC,GYÁL,GYOMAENDRŐD,GYÖMRŐ,GYÖNGYÖS,GYÖNGYÖSPATA,GYÖNK,GYŐR,GYULA,HAJDÚBÖSZÖRMÉNY,HAJDÚDOROG,HAJDÚHADHÁZ,HAJDÚNÁNÁS,HAJDÚSÁMSON,HAJDÚSZOBOSZLÓ,HAJÓS,HALÁSZTELEK,HARKÁNY,HATVAN,
	HEREND,HEVES,HÉVÍZ,HÓDMEZŐÁSÁRHELY,IBRÁNY,IGAL,ISASZEG,IZSÁK,JÁNOSHALMA,JÁNOSHÁZA,JÁNOSSOMORJA,JÁSZAPÁTI,JÁSZÁROKSZÁLLÁS,JÁSZBERÉNY,JÁSZFÉNYSZARU,JÁSZKISÉR,KABA,KADARKÚT,KALOCSA,
	KAPOSVÁR,KAPUVÁR,KARCAG,KAZINCARCIKA,KECEL,KECSKEMÉT,KEMECSE,KENDERES,KEREKEGYHÁZA,KEREPES,KESZTHELY,KISBÉR,KISKÖRE,KISKŐRÖS,KISKUNFÉLEGYHÁZA,KISKUNHALAS,KISKUNMAJSA,KISTARCSA,
	KISTELEK,KISÚJSZÁLLÁS,KISVÁRDA,KOMÁDI,KOMÁROM,KOMLÓ,KONDOROS,KOZÁRMISLENY,KÖRMEND,KÖRÖSLADÁNY,KŐSZEG,KUNHEGYES,KUNSZENTMÁRTON,KUNSZENTMIKLÓS,LÁBATLAN,LAJOSMIZSE,LÉBÉNY,LENGYELTÓTI,
	LENTI,LÉTAVÉRTES,LETENYE,LŐRINCI,MAGLÓD,MÁGOCS,MAKÓ,MÁNDOK,MARCALI,MÁRIAPÓCS,MARTFŰ,MARTONVÁSÁR,MÁTÉSZALKA,MEDGYESEGYHÁZA,MÉLYKÚT,MEZŐBERÉNY,MEZŐCSÁT,MEZŐHEGYES,MEZŐKERESZTES,
	MEZŐKOVÁCSHÁZA,MEZŐKÖVESD,MEZŐTÚR,MINDSZENT,MISKOLC,MOHÁCS,MONOR,MÓR,MÓRAHALOM,MOSONMAGYARÓVÁR,NÁDUDVAR,NAGYATÁD,NAGYBAJOM,NAGYECSED,NAGYHALÁSZ,NAGYKÁLLÓ,NAGYKANIZSA,NAGYKÁTA,
	NAGYKŐRÖS,NAGYMÁNYOK,NAGYMAROS,NYÉKLÁDHÁZA,NYERGESÚJFALU,NYÍRADONY,NYÍRBÁTOR,NYÍREGYHÁZA,NYÍRLUGOS,NYÍRMADA,NYÍRTELEK,ÓCSA,ONGA,OROSHÁZA,OROSZLÁNY,ÓZD,ŐRBOTTYÁN,ŐRISZENTPÉTER,
	ÖRKÉNY,PACSA,PAKS,PÁLHÁZA,PANNONHALMA,PÁPA,PÁSZTÓ,PÉCEL,PÉCS,PÉCSVÁRAD,PÉTERVÁSÁRA,PILIS,PILISCSABA,PILISVÖRÖSVÁR,POLGÁR,POLGÁRDI,POMÁZ,PUSZTASZABOLCS,PUTNOK,PÜSPÖKLADÁNY,RÁCALMÁS,
	RÁCKEVE,RAKAMAZ,RÁKÓCZIFALVA,RÉPCELAK,RÉTSÁG,RUDABÁNYA,SAJÓBÁBONY,SAJÓSZENTPÉTER,SALGÓTARJÁN,SÁNDORFALVA,SÁRBOGÁRD,SARKAD,SÁROSPATAK,SÁRVÁR,SÁSD,SÁTORALJAÚJHELY,SELLYE,SIKLÓS,
	SIMONTORNYA,SIÓFOK,SOLT,SOLTVADKERT,SOPRON,SÜLYSÁP,SÜMEG,SZABADSZÁLLÁS,SZARVAS,SZÁZHALOMBATTA,SZÉCSÉNY,SZEGED,SZEGHALOM,SZÉKESFEHÉRVÁR,SZEKSZÁRD,SZENDRŐ,SZENTENDRE,SZENTES,
	SZENTGOTTHÁRD,SZENTLŐRINC,SZERENCS,SZIGETHALOM,SZIGETSZENTMIKLÓS,SZIGETVÁR,SZIKSZÓ,SZOB,SZOLNOK,SZOMBATHELY,TAB,TAMÁSI,TÁPIÓSZELE,TAPOLCA,TÁT,TATA,TATABÁNYA,TÉGLÁS,TÉT,TISZACSEGE,
	TISZAFÖLDVÁR,TISZAFÜRED,TISZAKÉCSKE,TISZALÖK,TISZAÚJVÁROS,TISZAVASVÁRI,TOKAJ,TOLNA,TOMPA,TÓTKOMLÓS,TÖKÖL,TÖRÖKBÁLINT,TÖRÖKSZENTMIKLÓS,TURA,TÚRKEVE,ÚJFEHÉRTÓ,ÚJHARTYÁN,ÚJKÍGYÓS,ÚJSZÁSZ,
	ÜLLŐ,VÁC,VAJA,VÁMOSPÉRCS,VÁRPALOTA,VÁSÁROSNAMÉNY,VASVÁR,VECSÉS,VELENCE,VÉP,VERESEGYHÁZ,VERPELÉT,VESZPRÉM,VÉSZTŐ,VILLÁNY,VISEGRÁD,ZÁHONY,ZALAEGERSZEG,ZALAKAROS,ZALALÖVŐ,ZALASZENTGRÓT,
	ZAMÁRDI,ZIRC,ZSÁMBÉK;
}
