public enum Street {
	BARTÓK_BÉLA, MÓRIZS_ZSIGMOND, FERENC, TERÉZ, ADY_ENDRE, KOSSUTH, FEHÉRVÁRI, ETELE, BUDAFOKI, GÁRDONYI_GÉZA, DOBÓ_ISTVÁN, BORNEMISSZA, BORNEMISSZA_GERGELY, 
	JÓKAI_MÓR, ALBERT_FERENC, ÁLLOMÁS, ALMAGYAR, ALMÁSY_PÁL, ANDRÁS_BÍRÓ, ANKLI_JÓZSEF, ATTILA, BABÓCSAY_SÁNDOR, BAJCSY_ZSILINSZKY_ENDRE, BALASSI_BÁLINT, BARKÓCZY, 
	BARTAKOVICS, BARTALOS_GYULA, BERCSÉNYI_MIKLÓS, BERZE_NAGY_JÁNOS, BERZEVICZY_GIZELLA, BLASKOVICS_GYULA, BOLYKI_TAMÁS, BORSITZ_JÁNOS, BREZNAY_IMRE, BRÓDY_SÁNDOR, 
	CECEY_ÉVA, CIFRAKAPU, CSIKY_SÁNDOR, DAYKA_GÁBOR, DEÁK_FERENC, DOMOKOS_JAKAB, DÓZSA_GYÖRGY, DR_HIBAY_KÁROLY, DR_KAPOR_ELEMÉR, DR_NAGY_JÁNOS, DR_SÁNDOR_IMRE, 
	EGÉSZSÉGHÁZ, ERDÉLYI_ÉVA, ÉRSEK, ESZTERHÁZY, FAZOLA_HENRIK, FELLNER_JAKAB, FOGLÁR_GYÖRGY, FRANK_TIVADAR, FÜGEDY_JÁNOS, FÜRDŐ, GERL_MÁTYÁS, GÓLYA, GOROVE_LÁSZLÓ, 
	GRÓNAY_SÁNDOR, HARANGÖNTŐ, HATVANAS_EZRED, HATVANI_KAPU, HELL_MIKSA, HEVESI_SÁNDOR, IPOLYI_ARNOLD, JANKOVICS_DEZSŐ, JOÓ_JÁNOS, KÁLNOKY, KANDRA_KABOS, 
	KATONA_ISTVÁN, KEGLEVICH_MIKLÓS, KERTÉSZ, KILIÁN_ISTVÁN, KIRÁLY, KLAPKA_GYÖRGY, KNÉZICH_KÁROLY, KOCSIS_BERNÁT, KOHÁRY_ISTVÁN, LÁJER_DEZSŐ, LEGÁNYI_FERENC, 
	LENKEY_JÁNOS, LUDÁNYI_ANTAL, MACZKI_VALÉR, MALOM, MARKHOT_FERENC, MEKCSEY, MIKES_KELEMEN, MINDSZENTY_GEDEON, MLINKÓ_MÁTYÁS, MOCSÁRY_LAJOS, NEUMAYER_JÁNOS, 
	PÁPAY_SÁMUEL, PETŐ_GÁSPÁR, PETŐFI_SÁNDOR, PUKY_MIKLÓS, PYRKER, RÁCKAPU, RAJNER_KÁROLY, REMÉNYI_EDE, REMENYIK_ZSIGMOND, RÓKUS, ROTTENSTEIN_KÁROLY, ROZÁLIA, 
	RÓZSA_KÁROLY, SERVITA, STADION, SUGÁR_ISTVÁN, SZAICZ_LEÓ, SZÁLLODA, SZARVAS, SZARVAS_GÁBOR, SZÉCHENYI_ISTVÁN, SZEDERKÉNYI_NÁNDOR, SZENT_JÁNOS, SZÉPASSZONYVÖLGY, 
	SZOLÁRCSIK_SÁNDOR, SZVORÉNYI, TÁRKÁNYI_BÉLA, TAVASSY_ANTAL, TELEKESSY_ISTVÁN, TIBA_ISTVÁN, TINÓDI_SEBESTYÉN, TITTEL_PÁL, TIZESHONVÉD, TORDAI_ÁNYOS, TÖRVÉNYHÁZ, 
	TRINITÁRIUS, TÜNDÉRPART, TÜRK_FRIGYES, TŰZOLTÓ, VALLON, VÁLYI_ISTVÁN, VÁROSFAL, VASÖNTŐ, VÉCSEY_SÁNDOR, VINCELLÉRISKOLA, VITKOVICS_MIHÁLY, ZALÁR_JÓZSEF, ZOLTAY_ISTVÁN;
}